

import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar"; 
import Footer from "@/components/Footer";
const inter = Inter({ subsets: ["latin"] });
import Providerdata from "./wrapper/provider";
import { AuthProvider } from "./Redux/authcontex";
import { Toaster } from "react-hot-toast";
export const metadata = {
  title: "PIZZA-VIZZA",
  description: "Generated by create next app",
  icons: {
    icon: './favicon.ico', 
  },
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
        <Providerdata >
          
        <Navbar />
        <div className="overflow-y-auto  scrollable-container  overflow-x-hidden h-[85vh] w-full bg-[#000000] bg-[radial-gradient(#ffffff33_1px,#00091d_1px)] bg-[size:20px_20px] text-white">
        <Toaster position="top-right" />
          {children}
        </div>
        <Footer />
        </Providerdata>
        </AuthProvider>
      </body>
    </html>
  );
}
